from arcticdb.config import *
from arcticdb.config import *
from arcticdb.config import Defaults as _Defaults


#  TODO - After the initial migration we will migrate credentials in here to Vault


_DEFAULT_MONGO_ENV = "research"
_DEFAULT_LIB_COLL = "arcticc_lib_config"
_DEFAULT_STORAGE_COLL = "arcticc_storage_config"
_DEFAULT_LIB_META_COLL = "arcticc_lib_metadata"
_DEFAULT_ARCTIC_NATIVE_CONFIG_DB = "arctic_native_config"
_DEFAULT_MONGO_URI = "mongodb://localhost:27017"
_DEFAULT_S3_BUCKET = "alpha-data-dev-arcticnative-ahl-research-3"
_DEFAULT_S3_MKTDATAD_BUCKET = "alpha-data-dev-arcticnative-ahl-mktdatad-2"
_DEFAULT_S3_ENDPOINT = "arctic-data.vast.gdc.storage.res.m"
_DEFAULT_S3_CREDENTIALS = "7845QS3YTS7746EP6QLX"
_DEFAULT_S3_KEY = "Tm1tMAs6snq6HjBOnkpDIRjAEdlg4A8PlrWn6+/g"
_DEFAULT_S3_MKTDATAD_CREDENTIALS = "YVCRCVRUR92IYUF523WQ"
_DEFAULT_S3_MKTDATAD_KEY = "WtMWYr0XQtvPuVl7mtiDARgpMeLdKLci0S7cl7CR"
_DEFAULT_S3_NUMERIC_BUCKET = "alpha-data-dev-arcticnative-num-res-1"
_DEFAULT_S3_NUMERIC_ENDPOINT = "s3.mxg.res.m"
_DEFAULT_S3_NUMERIC_CREDENTIALS = "PSFBSAZRHILCCKNAONCJIOJMOIPKMFIGNENKPBDPMN"
_DEFAULT_S3_NUMERIC_KEY = "67401FAD4d685caf8/83cb+EB0ADCC3918da931NMHG"
_DEFAULT_VAST_ENDPOINT = "data.vast.gdc.storage.res.m"
_DEFAULT_PUSHGATEWAY_URL = "prometheus.res.ahl:9091"
_DEFAULT_PUSH_JOB_NAME = "arcticc"
_DEFAULT_PUSHGATEWAY_ENV_VAR = "PROMETHEUS_GATEWAY"
_DEFAULT_PROMETHUES_ENV_VAR = "PROMETHEUS_ENVIRONMENT"
_DEFAULT_PROMETHEUS_ENV_VALUE = "res"
_DEFAULT_PROMETHEUS_MODE = 1
_DEFAULT_EVENT_TYPE = "arctic_native"
_DEFAULT_EVENT_LOGGER_ENV_VAR = "EVENT_LOGGER_URL"
_DEFAULT_EVENT_LOGGER_URL = "ahl-event-logger.maninvestments.com:1180"
_VAST_ENDPOINT_TOKEN = ".vast."

# User options
_DEFAULT_PRUNE_PREVIOUS = False
_DEFAULT_DYNAMIC_STRINGS = False
_DEFAULT_RECURSIVE_NORMALIZERS = False
_DEFAULT_PICKLE_ON_FAILURE = False

# Feature flags
_DEFAULT_SYMBOL_LIST = False
_DEFAULT_DEDUPLICATION = False

# Vast migration
_MIGRATION_VAST_USER = "VY4RYVS6TYTXV4G91455"
_MIGRATION_VAST_SECRET = "SQa2UsMDk7UVa4B0nHSKncmTYidiFvTk+8Qa7M6c"
_MIGRATION_VAST_ENDPOINT = "arctic-data.vast.gdc.storage.res.m"
_MIGRATION_VAST_BUCKET = "alpha-data-dev-arcticnative-ahl-research-1"

VERSION_STORE = "VersionStore"


class Defaults(_Defaults):
    MONGO_ENV = _DEFAULT_MONGO_ENV
    ARCTIC_NATIVE_CONFIG_DB = _DEFAULT_ARCTIC_NATIVE_CONFIG_DB
    DEFAULT_LIB_COLL = _DEFAULT_LIB_COLL
    DEFAULT_STORAGE_COLL = _DEFAULT_STORAGE_COLL
    DEFAULT_LIB_META_COLL = _DEFAULT_LIB_META_COLL
    DEFAULT_LIB_ID_NAME = "library"
    DEFAULT_STORAGE_ID_NAME = "storage"
    DEFAULT_MONGO_URI = _DEFAULT_MONGO_URI
    DEFAULT_S3_BUCKET = _DEFAULT_S3_BUCKET
    DEFAULT_S3_MKTDATAD_BUCKET = _DEFAULT_S3_MKTDATAD_BUCKET
    DEFAULT_S3_ENDPOINT = _DEFAULT_S3_ENDPOINT
    DEFAULT_S3_CREDENTIALS = _DEFAULT_S3_CREDENTIALS
    DEFAULT_S3_KEY = _DEFAULT_S3_KEY
    DEFAULT_S3_MKTDATAD_CREDENTIALS = _DEFAULT_S3_MKTDATAD_CREDENTIALS
    DEFAULT_S3_MKTDATAD_KEY = _DEFAULT_S3_MKTDATAD_KEY
    DEFAULT_VAST_ENDPOINT = _DEFAULT_VAST_ENDPOINT
    DEFAULT_PRUNE_PREVIOUS = _DEFAULT_PRUNE_PREVIOUS
    DEFAULT_RECURSIVE_NORMALIZERS = _DEFAULT_RECURSIVE_NORMALIZERS
    DEFAULT_PICKLE_ON_FAILURE = _DEFAULT_PICKLE_ON_FAILURE
    DEFAULT_SYMBOL_LIST = _DEFAULT_SYMBOL_LIST
    DEFAULT_DEDUPLICATION = _DEFAULT_DEDUPLICATION
    DEFAULT_DYNAMIC_STRINGS = _DEFAULT_DYNAMIC_STRINGS
    DEFAULT_PUSHGATEWAY_URL = _DEFAULT_PUSHGATEWAY_URL
    DEFAULT_PUSH_JOB_NAME = _DEFAULT_PUSH_JOB_NAME
    DEFAULT_PUSHGATEWAY_ENV_VAR = _DEFAULT_PUSHGATEWAY_ENV_VAR
    DEFAULT_PROMETHUES_ENV_VAR = _DEFAULT_PROMETHUES_ENV_VAR
    DEFAULT_PROMETHEUS_ENV_VALUE = _DEFAULT_PROMETHEUS_ENV_VALUE
    DEFAULT_PROMETHEUS_MODE = _DEFAULT_PROMETHEUS_MODE
    DEFAULT_EVENT_TYPE = _DEFAULT_EVENT_TYPE
    DEFAULT_EVENT_LOGGER_ENV_VAR = _DEFAULT_EVENT_LOGGER_ENV_VAR
    DEFAULT_EVENT_LOGGER_URL = _DEFAULT_EVENT_LOGGER_URL
    DEFAULT_S3_NUMERIC_BUCKET = _DEFAULT_S3_NUMERIC_BUCKET
    DEFAULT_S3_NUMERIC_ENDPOINT = _DEFAULT_S3_NUMERIC_ENDPOINT
    DEFAULT_S3_NUMERIC_CREDENTIALS = _DEFAULT_S3_NUMERIC_CREDENTIALS
    DEFAULT_S3_NUMERIC_KEY = _DEFAULT_S3_NUMERIC_KEY
    DEFAULT_MIGRATION_VAST_USER = _MIGRATION_VAST_USER
    DEFAULT_MIGRATION_VAST_SECRET = _MIGRATION_VAST_SECRET
    DEFAULT_MIGRATION_VAST_ENDPOINT = _MIGRATION_VAST_ENDPOINT
    DEFAULT_MIGRATION_VAST_BUCKET = _MIGRATION_VAST_BUCKET
    DEFAULT_VAST_ENDPOINT_TOKEN = _VAST_ENDPOINT_TOKEN
